name: Deploy Deno branch
on:
    push:
        branches:
            - main
        paths:
            - deno/**
jobs:
    copy:
        name: Deploy Deno
        runs-on: ubuntu-latest
        steps:
            - name: Set up Actions
                uses: actions/checkout@v2

            - name: Set up Deno
                uses: denoland/setup-deno@v1.0.0
                with:
                deno-version: v1.x

            - name: Analyze code
                run: deno lint ./deno

            - name: Run unit and integration tests
                run: deno test -A ./deno/tests

            - name: Deploy
                uses: JamesIves/github-pages-deploy-action@4.1.0
                with:
                    branch: deno
                    folder: deno

            - name: Publish
                uses: actions/upload-artifact@v2
                with:
                    name: published
                    path: deno
